namespace MAX_CMSS_V2
{
    using Logic;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class Query_OperatorLog : UserControl
    {
        private IContainer components = null;
        private QueryPanel queryPanel1;
        private QueryPanel queryPanel10;
        private QueryPanel queryPanel11;
        private QueryPanel queryPanel2;
        private QueryPanel queryPanel3;
        private QueryPanel queryPanel4;
        private QueryPanel queryPanel5;
        private QueryPanel queryPanel6;
        private QueryPanel queryPanel7;
        private QueryPanel queryPanel8;
        private QueryPanel queryPanel9;
        private TabControl tabControl1;
        private TabPage tabPage1;
        private TabPage tabPage10;
        private TabPage tabPage11;
        private TabPage tabPage2;
        private TabPage tabPage3;
        private TabPage tabPage4;
        private TabPage tabPage5;
        private TabPage tabPage6;
        private TabPage tabPage7;
        private TabPage tabPage8;
        private TabPage tabPage9;

        public Query_OperatorLog()
        {
            this.InitializeComponent();
            this.queryPanel1.LogType = LogType.CeDianPeiZhi;
            this.queryPanel2.LogType = LogType.FenZhanPeiZhi;
            this.queryPanel3.LogType = LogType.GuZhangBiSuo;
            this.queryPanel4.LogType = LogType.FengDianWaSiBiSuo;
            this.queryPanel5.LogType = LogType.ShouDongKongZhi;
            this.queryPanel6.LogType = LogType.JiaoShi;
            this.queryPanel7.LogType = LogType.MoNiLiang;
            this.queryPanel8.LogType = LogType.KaiGuanLiang;
            this.queryPanel9.LogType = LogType.DuoSheBei;
            this.queryPanel10.LogType = LogType.KuiDianGuanXi;
            this.queryPanel11.LogType = LogType.KongZhiLuoJi;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tabControl1 = new TabControl();
            this.tabPage1 = new TabPage();
            this.queryPanel1 = new QueryPanel();
            this.tabPage2 = new TabPage();
            this.queryPanel2 = new QueryPanel();
            this.tabPage3 = new TabPage();
            this.queryPanel3 = new QueryPanel();
            this.tabPage4 = new TabPage();
            this.queryPanel4 = new QueryPanel();
            this.tabPage5 = new TabPage();
            this.queryPanel5 = new QueryPanel();
            this.tabPage6 = new TabPage();
            this.queryPanel6 = new QueryPanel();
            this.tabPage7 = new TabPage();
            this.queryPanel7 = new QueryPanel();
            this.tabPage8 = new TabPage();
            this.queryPanel8 = new QueryPanel();
            this.tabPage9 = new TabPage();
            this.queryPanel9 = new QueryPanel();
            this.tabPage10 = new TabPage();
            this.queryPanel10 = new QueryPanel();
            this.tabPage11 = new TabPage();
            this.queryPanel11 = new QueryPanel();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.tabPage5.SuspendLayout();
            this.tabPage6.SuspendLayout();
            this.tabPage7.SuspendLayout();
            this.tabPage8.SuspendLayout();
            this.tabPage9.SuspendLayout();
            this.tabPage10.SuspendLayout();
            this.tabPage11.SuspendLayout();
            base.SuspendLayout();
            this.tabControl1.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Controls.Add(this.tabPage5);
            this.tabControl1.Controls.Add(this.tabPage6);
            this.tabControl1.Controls.Add(this.tabPage7);
            this.tabControl1.Controls.Add(this.tabPage8);
            this.tabControl1.Controls.Add(this.tabPage9);
            this.tabControl1.Controls.Add(this.tabPage10);
            this.tabControl1.Controls.Add(this.tabPage11);
            this.tabControl1.Location = new Point(0, 0);
            tabControl1.Padding = new System.Drawing.Point(5, 5);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x413, 0x1fc);
            this.tabControl1.TabIndex = 0;
            this.tabControl1.Font = new Font("宋体", 10.5f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.tabControl1.ItemSize = new System.Drawing.Size(110, 30);
            this.tabPage1.Controls.Add(this.queryPanel1);
            this.tabPage1.Location = new Point(4, 0x16);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(10);
            this.tabPage1.Size = new Size(0x40b, 0x1e2);
            this.tabPage1.TabIndex = 0;
            //this.tabPage1.h = new Font("宋体", 10.5f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.tabPage1.Text = "测点配置";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tabPage1.Click += new EventHandler(this.tabPage1_Click);
            this.queryPanel1.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel1.AutoScroll = true;
            this.queryPanel1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel1.Location = new Point(6, 6);
            this.queryPanel1.LogType = LogType.TiaoJiao;
            this.queryPanel1.Name = "queryPanel1";
            this.queryPanel1.Size = new Size(0x409, 0x1dd);
            this.queryPanel1.TabIndex = 1;
            this.tabPage2.Controls.Add(this.queryPanel2);
            this.tabPage2.Location = new Point(4, 0x16);
            this.tabPage2.Name = "tabPage2";
           // this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(0x40b, 0x1e2);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "分站配置";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.queryPanel2.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel2.AutoScroll = true;
            this.queryPanel2.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel2.Location = new Point(6, 6);
            this.queryPanel2.LogType = LogType.TiaoJiao;
            this.queryPanel2.Name = "queryPanel2";
            this.queryPanel2.Size = new Size(0x3ff, 0x1e1);
            this.queryPanel2.TabIndex = 0;
            this.tabPage3.Controls.Add(this.queryPanel3);
            this.tabPage3.Location = new Point(4, 0x16);
            this.tabPage3.Name = "tabPage3";
           // this.tabPage3.Padding = new Padding(3);
            this.tabPage3.Size = new Size(0x40b, 0x1e2);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "故障闭锁";
            this.tabPage3.UseVisualStyleBackColor = true;
            this.queryPanel3.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel3.AutoScroll = true;
            this.queryPanel3.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel3.Location = new Point(0, 6);
            this.queryPanel3.LogType = LogType.TiaoJiao;
            this.queryPanel3.Name = "queryPanel3";
            this.queryPanel3.Size = new Size(0x405, 0x1da);
            this.queryPanel3.TabIndex = 0;
            this.tabPage4.Controls.Add(this.queryPanel4);
            this.tabPage4.Location = new Point(4, 0x16);
            this.tabPage4.Name = "tabPage4";
           // this.tabPage4.Padding = new Padding(3);
            this.tabPage4.Size = new Size(0x40b, 0x1e2);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "风电瓦斯闭锁";
            this.tabPage4.UseVisualStyleBackColor = true;
            this.queryPanel4.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel4.AutoScroll = true;
            this.queryPanel4.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel4.Location = new Point(6, 6);
            this.queryPanel4.LogType = LogType.TiaoJiao;
            this.queryPanel4.Name = "queryPanel4";
            this.queryPanel4.Size = new Size(0x405, 0x1e1);
            this.queryPanel4.TabIndex = 0;
            this.tabPage5.Controls.Add(this.queryPanel5);
            this.tabPage5.Location = new Point(4, 0x16);
            this.tabPage5.Name = "tabPage5";
           // this.tabPage5.Padding = new Padding(3);
            this.tabPage5.Size = new Size(0x40b, 0x1e2);
            this.tabPage5.TabIndex = 4;
            this.tabPage5.Text = "手动控制";
            this.tabPage5.UseVisualStyleBackColor = true;
            this.queryPanel5.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel5.AutoScroll = true;
            this.queryPanel5.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel5.Location = new Point(6, 6);
            this.queryPanel5.LogType = LogType.TiaoJiao;
            this.queryPanel5.Name = "queryPanel5";
            this.queryPanel5.Size = new Size(0x406, 0x1de);
            this.queryPanel5.TabIndex = 0;
            this.tabPage6.Controls.Add(this.queryPanel6);
            this.tabPage6.Location = new Point(4, 0x16);
            this.tabPage6.Name = "tabPage6";
          //  this.tabPage6.Padding = new Padding(3);
            this.tabPage6.Size = new Size(0x40b, 0x1e2);
            this.tabPage6.TabIndex = 5;
            this.tabPage6.Text = "校时操作";
            this.tabPage6.UseVisualStyleBackColor = true;
            this.queryPanel6.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel6.AutoScroll = true;
            this.queryPanel6.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel6.Location = new Point(6, 6);
            this.queryPanel6.LogType = LogType.TiaoJiao;
            this.queryPanel6.Name = "queryPanel6";
            this.queryPanel6.Size = new Size(0x402, 0x1da);
            this.queryPanel6.TabIndex = 0;
            this.tabPage7.Controls.Add(this.queryPanel7);
            this.tabPage7.Location = new Point(4, 0x16);
            this.tabPage7.Name = "tabPage7";
          //  this.tabPage7.Padding = new Padding(3);
            this.tabPage7.Size = new Size(0x40b, 0x1e2);
            this.tabPage7.TabIndex = 6;
            this.tabPage7.Text = "模拟量";
            this.tabPage7.UseVisualStyleBackColor = true;
            this.queryPanel7.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel7.AutoScroll = true;
            this.queryPanel7.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel7.Location = new Point(6, 6);
            this.queryPanel7.LogType = LogType.TiaoJiao;
            this.queryPanel7.Name = "queryPanel7";
            this.queryPanel7.Size = new Size(0x405, 0x1e1);
            this.queryPanel7.TabIndex = 0;
            this.tabPage8.Controls.Add(this.queryPanel8);
            this.tabPage8.Location = new Point(4, 0x16);
            this.tabPage8.Name = "tabPage8";
           // this.tabPage8.Padding = new Padding(3);
            this.tabPage8.Size = new Size(0x40b, 0x1e2);
            this.tabPage8.TabIndex = 7;
            this.tabPage8.Text = "开关量";
            this.tabPage8.UseVisualStyleBackColor = true;
            this.queryPanel8.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel8.AutoScroll = true;
            this.queryPanel8.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel8.Location = new Point(6, 6);
            this.queryPanel8.LogType = LogType.TiaoJiao;
            this.queryPanel8.Name = "queryPanel8";
            this.queryPanel8.Size = new Size(0x409, 0x1da);
            this.queryPanel8.TabIndex = 0;
            this.tabPage9.Controls.Add(this.queryPanel9);
            this.tabPage9.Location = new Point(4, 0x16);
            this.tabPage9.Name = "tabPage9";
           // this.tabPage9.Padding = new Padding(3);
            this.tabPage9.Size = new Size(0x40b, 0x1e2);
            this.tabPage9.TabIndex = 8;
            this.tabPage9.Text = "多设备联动报警";
            this.tabPage9.UseVisualStyleBackColor = true;
            this.queryPanel9.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel9.AutoScroll = true;
            this.queryPanel9.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel9.Location = new Point(6, 6);
            this.queryPanel9.LogType = LogType.TiaoJiao;
            this.queryPanel9.Name = "queryPanel9";
            this.queryPanel9.Size = new Size(0x3ff, 0x1e1);
            this.queryPanel9.TabIndex = 0;
            this.tabPage10.Controls.Add(this.queryPanel10);
            this.tabPage10.Location = new Point(4, 0x16);
            this.tabPage10.Name = "tabPage10";
          //  this.tabPage10.Padding = new Padding(3);
            this.tabPage10.Size = new Size(0x40b, 0x1e2);
            this.tabPage10.TabIndex = 9;
            this.tabPage10.Text = "馈电关系";
            this.tabPage10.UseVisualStyleBackColor = true;
            this.queryPanel10.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel10.AutoScroll = true;
            this.queryPanel10.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel10.Location = new Point(6, 6);
            this.queryPanel10.LogType = LogType.TiaoJiao;
            this.queryPanel10.Name = "queryPanel10";
            this.queryPanel10.Size = new Size(0x405, 0x1dd);
            this.queryPanel10.TabIndex = 0;
            this.tabPage11.Controls.Add(this.queryPanel11);
            this.tabPage11.Location = new Point(4, 0x16);
            this.tabPage11.Name = "tabPage11";
           // this.tabPage11.Padding = new Padding(3);
            this.tabPage11.Size = new Size(0x40b, 0x1e2);
            this.tabPage11.TabIndex = 10;
            this.tabPage11.Text = "控制逻辑关系";
            this.tabPage11.UseVisualStyleBackColor = true;
            this.queryPanel11.Anchor = System.Windows.Forms.AnchorStyles.Right | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Top;
            this.queryPanel11.AutoScroll = true;
            this.queryPanel11.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink; 
            this.queryPanel11.Location = new Point(6, 6);
            this.queryPanel11.LogType = LogType.TiaoJiao;
            this.queryPanel11.Name = "queryPanel11";
            this.queryPanel11.Size = new Size(0x406, 0x1e1);
            this.queryPanel11.TabIndex = 0;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
             base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.tabControl1);
            base.Name = "Query_OperatorLog";
            base.Size = new Size(0x413, 0x1fc);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.tabPage5.ResumeLayout(false);
            this.tabPage6.ResumeLayout(false);
            this.tabPage7.ResumeLayout(false);
            this.tabPage8.ResumeLayout(false);
            this.tabPage9.ResumeLayout(false);
            this.tabPage10.ResumeLayout(false);
            this.tabPage11.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        private void tabPage1_Click(object sender, EventArgs e)
        {
        }
    }
}

